name: clip_castrate-ViT-L-14_imagenet_feature-simclr-mlp-sgd
dataset: 
  name: clip_castrate:ViT-L-14_imagenet_feature
  image_size: 224
  aug_num: 4 # -1 is maximize, 1 means no augmentation
  max_dataset_size: -1
  num_imagenet_classes: 1000
  imagenet_size: -1
  num_workers: 8

model: 
  name: simclr
  mean_std_name: clip
  backbone: projection_MLP-1024-2 # in_dim, layer number

eval: # linear evaluation, False will turn off automatic evaluation after training
  optimizer: 
    name: sgd
    weight_decay: 0.0005
    momentum: 0.9 # useless for adam
  warmup_lr: 0
  warmup_epochs: 0
  base_lr: 0.06
  final_lr: 0
  batch_size: 256
  num_epochs: 200
  theta: 0.1

logger:
  tensorboard: False
  matplotlib: False

# two things might lead to stochastic behavior other than seed:
# worker_init_fn from dataloader and torch.nn.functional.interpolate 
# (keep this in mind if you want to achieve 100% deterministic)





